version: 2
updates:
  # Enable version updates for pip (Python backend)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainer-username"  # Replace with actual GitHub username
    assignees:
      - "maintainer-username"  # Replace with actual GitHub username
    commit-message:
      prefix: "backend"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "python"

  # Enable version updates for npm (Frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainer-username"  # Replace with actual GitHub username
    assignees:
      - "maintainer-username"  # Replace with actual GitHub username
    commit-message:
      prefix: "frontend"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "javascript"
    ignore:
      # Ignore major version updates for these packages (can be removed if desired)
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "maintainer-username"  # Replace with actual GitHub username
    assignees:
      - "maintainer-username"  # Replace with actual GitHub username
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"