# Generated by Django 4.2.9 on 2025-02-28 07:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Task Title')),
                ('description', models.TextField(blank=True, verbose_name='Task Description')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('DEPRECATED', 'Deprecated')], default='DRAFT', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_submissions', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Submissions')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Task Deadline')),
                ('points_possible', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('passing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('task_type', models.CharField(default='generic', max_length=50)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_tasks', to='courses.course')),
            ],
            options={
                'verbose_name': 'Learning Task',
                'verbose_name_plural': 'Learning Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentTask',
            fields=[
                ('learningtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.learningtask')),
                ('assessment_type', models.CharField(choices=[('TEXT', 'Text Submission'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('FILE', 'File Upload')], default='TEXT', max_length=50)),
            ],
            options={
                'verbose_name': 'Assessment Task',
                'verbose_name_plural': 'Assessment Tasks',
            },
            bases=('tasks.learningtask',),
        ),
        migrations.CreateModel(
            name='QuizTask',
            fields=[
                ('learningtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.learningtask')),
                ('quiz_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TRUE_FALSE', 'True/False'), ('SHORT_ANSWER', 'Short Answer')], default='MULTIPLE_CHOICE', max_length=50)),
            ],
            options={
                'verbose_name': 'Quiz Task',
                'verbose_name_plural': 'Quiz Tasks',
            },
            bases=('tasks.learningtask',),
        ),
    ]
