# Generated by Django 4.2.9 on 2025-02-27 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Task Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Task Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Maximum Score",
                    ),
                ),
                (
                    "passing_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Passing Score",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuizTask",
            fields=[
                (
                    "assessmenttask_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tasks.assessmenttask",
                    ),
                ),
                (
                    "time_limit",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Time Limit (minutes)"
                    ),
                ),
                (
                    "is_randomized",
                    models.BooleanField(
                        default=False, verbose_name="Randomize Question Order"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("tasks.assessmenttask",),
        ),
        migrations.CreateModel(
            name="LearningTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Task Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Task Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Task Status",
                    ),
                ),
                (
                    "max_submissions",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Maximum Submissions"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Task Deadline"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Difficulty Level"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Task",
                "verbose_name_plural": "Learning Tasks",
                "indexes": [
                    models.Index(
                        fields=["course", "status"],
                        name="tasks_learn_course__d4e167_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="tasks_learn_created_1e1af9_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="tasks_learn_updated_535d57_idx"
                    ),
                    models.Index(
                        fields=["deadline"], name="tasks_learn_deadlin_b04ee0_idx"
                    ),
                ],
            },
        ),
    ]
