# Generated by Django 4.2.9 on 2025-02-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssessmentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Task Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Task Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Maximum Score",
                    ),
                ),
                (
                    "passing_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Passing Score",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LearningTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Task Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Task Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "difficulty_level",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Difficulty Level"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuizTask",
            fields=[
                (
                    "assessmenttask_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tasks.assessmenttask",
                    ),
                ),
                (
                    "time_limit",
                    models.IntegerField(null=True, verbose_name="Time Limit (minutes)"),
                ),
                (
                    "is_randomized",
                    models.BooleanField(
                        default=False, verbose_name="Randomize Question Order"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("tasks.assessmenttask",),
        ),
    ]
