# Generated by Django 4.2.9 on 2025-02-28 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='learningtask',
            index=models.Index(fields=['course', 'status'], name='tasks_learn_course__d4e167_idx'),
        ),
        migrations.AddIndex(
            model_name='learningtask',
            index=models.Index(fields=['created_at'], name='tasks_learn_created_1e1af9_idx'),
        ),
        migrations.AddIndex(
            model_name='learningtask',
            index=models.Index(fields=['updated_at'], name='tasks_learn_updated_535d57_idx'),
        ),
        migrations.AddIndex(
            model_name='learningtask',
            index=models.Index(fields=['deadline'], name='tasks_learn_deadlin_b04ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='learningtask',
            index=models.Index(fields=['task_type'], name='tasks_learn_task_ty_a1a808_idx'),
        ),
    ]
