# Generated by Django 4.2.9 on 2025-02-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmenttask",
            name="max_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Maximum Score",
            ),
        ),
        migrations.AlterField(
            model_name="assessmenttask",
            name="passing_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Passing Score",
            ),
        ),
        migrations.AlterField(
            model_name="quiztask",
            name="time_limit",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Time Limit (minutes)"
            ),
        ),
    ]
