# Generated by Django 4.2.9 on 2025-02-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_quiz_tasks_alter_submission_graded_by_and_more'),
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmenttask',
            name='learningtask_ptr',
        ),
        migrations.RemoveField(
            model_name='quiztask',
            name='learningtask_ptr',
        ),
        migrations.RemoveIndex(
            model_name='learningtask',
            name='tasks_learn_course__d4e167_idx',
        ),
        migrations.RemoveIndex(
            model_name='learningtask',
            name='tasks_learn_created_1e1af9_idx',
        ),
        migrations.RemoveIndex(
            model_name='learningtask',
            name='tasks_learn_updated_535d57_idx',
        ),
        migrations.RemoveIndex(
            model_name='learningtask',
            name='tasks_learn_deadlin_b04ee0_idx',
        ),
        migrations.RemoveIndex(
            model_name='learningtask',
            name='tasks_learn_task_ty_a1a808_idx',
        ),
        migrations.RemoveField(
            model_name='learningtask',
            name='settings',
        ),
        migrations.AddField(
            model_name='learningtask',
            name='requires_peer_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningtask',
            name='task_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible configuration for task-specific settings'),
        ),
        migrations.AlterField(
            model_name='learningtask',
            name='task_type',
            field=models.CharField(choices=[('TEXT_SUBMISSION', 'Text Submission'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('FILE_UPLOAD', 'File Upload'), ('QUIZ', 'Quiz'), ('PROJECT', 'Project'), ('DISCUSSION', 'Discussion')], default='TEXT_SUBMISSION', max_length=50),
        ),
        migrations.AddIndex(
            model_name='learningtask',
            index=models.Index(fields=['course', 'status', 'task_type'], name='tasks_learn_course__1da550_idx'),
        ),
        migrations.AddIndex(
            model_name='learningtask',
            index=models.Index(fields=['created_at', 'task_type'], name='tasks_learn_created_b34163_idx'),
        ),
        migrations.AddIndex(
            model_name='learningtask',
            index=models.Index(fields=['deadline', 'status'], name='tasks_learn_deadlin_3e6f45_idx'),
        ),
        migrations.AddIndex(
            model_name='learningtask',
            index=models.Index(fields=['created_by', 'task_type'], name='tasks_learn_created_186083_idx'),
        ),
        migrations.DeleteModel(
            name='AssessmentTask',
        ),
        migrations.DeleteModel(
            name='QuizTask',
        ),
    ]
