# Generated by Django 4.2.9 on 2025-02-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_assessmenttask_learningtask_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtask',
            name='max_word_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Word Count'),
        ),
        migrations.AddField(
            model_name='learningtask',
            name='min_word_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Word Count'),
        ),
        migrations.AddField(
            model_name='learningtask',
            name='text_submission_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for text submission tasks'),
        ),
    ]
