# Generated by Django 4.2.9 on 2025-02-28 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_learningtask_max_word_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadTaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_file_types', models.JSONField(blank=True, default=list, help_text="List of allowed file extensions (e.g. ['.pdf', '.docx', '.jpg'])")),
                ('max_file_size', models.PositiveIntegerField(default=10485760, help_text='Maximum file size in bytes')),
                ('max_files', models.PositiveIntegerField(default=1, help_text='Maximum number of files that can be uploaded')),
                ('require_description', models.BooleanField(default=False, help_text='Require students to provide a description for uploaded files')),
                ('virus_scan_required', models.BooleanField(default=True, help_text='Require virus scanning for uploaded files')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_config', to='tasks.learningtask')),
            ],
        ),
        migrations.CreateModel(
            name='FileSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded file for the task', upload_to='submissions/')),
                ('original_filename', models.CharField(help_text='Original filename of the uploaded file', max_length=255)),
                ('file_description', models.TextField(blank=True, help_text='Optional description for the uploaded file', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_submissions', to='tasks.learningtask')),
            ],
        ),
    ]
