# Generated by Django 4.2.9 on 2025-02-28 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_fileuploadtasktype_filesubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuizTaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(help_text='Total number of questions in the quiz')),
                ('questions_config', models.JSONField(default=list, help_text='Configuration for quiz questions. Each question should have: question text, options, correct answer(s)')),
                ('randomize_questions', models.BooleanField(default=False, help_text='Randomize the order of questions for each attempt')),
                ('randomize_options', models.BooleanField(default=False, help_text='Randomize the order of options for each question')),
                ('points_per_question', models.DecimalField(decimal_places=2, default=1.0, help_text='Points awarded for each correct answer', max_digits=5)),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='Maximum number of attempts allowed for the quiz')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_config', to='tasks.learningtask')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(help_text="Student's answers for each quiz question")),
                ('score', models.DecimalField(decimal_places=2, help_text='Score achieved in the quiz', max_digits=7)),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum possible score for the quiz', max_digits=7)),
                ('detailed_results', models.JSONField(help_text='Detailed breakdown of quiz results')),
                ('attempt_number', models.PositiveIntegerField(help_text='The attempt number for this quiz')),
                ('is_passed', models.BooleanField(help_text='Whether the student passed the quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_submissions', to='tasks.learningtask')),
            ],
            options={
                'verbose_name': 'Multiple Choice Quiz Submission',
                'verbose_name_plural': 'Multiple Choice Quiz Submissions',
                'ordering': ['-submission_time'],
                'indexes': [models.Index(fields=['task', 'student'], name='tasks_multi_task_id_2d9549_idx'), models.Index(fields=['submission_time'], name='tasks_multi_submiss_593747_idx')],
                'unique_together': {('task', 'student', 'attempt_number')},
            },
        ),
    ]
