# Generated by Django 4.2.9 on 2025-02-28 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='tasks.quiztask'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='assessment.quiz'),
        ),
    ]
