# Generated by Django 4.2.19 on 2025-02-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_options_alter_task_options_and_more"),
        ("assessment", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprogress",
            options={},
        ),
        migrations.RemoveField(
            model_name="submission",
            name="feedback",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="file",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="score",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="status",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="last_accessed",
        ),
        migrations.AddField(
            model_name="submission",
            name="grade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Grade",
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="submission",
            name="content",
            field=models.TextField(blank=True, verbose_name="Submission Content"),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="completed_tasks",
            field=models.ManyToManyField(
                related_name="completed_by", to="courses.task"
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="total_score",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Total Score"
            ),
        ),
    ]
