# Generated by Django 4.2.9 on 2025-02-28 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='tasks',
            field=models.ManyToManyField(blank=True, limit_choices_to={'task_type': 'MULTIPLE_CHOICE'}, related_name='assessment_quizzes', to='tasks.learningtask'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to='tasks.learningtask'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, limit_choices_to={'task_type': 'MULTIPLE_CHOICE'}, related_name='assessment_completed_by', to='tasks.learningtask'),
        ),
    ]
