# Generated by Django 4.2.9 on 2025-02-16 21:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Original course this was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_versions",
                to="learning.course",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="learning_objectives",
            field=models.TextField(
                blank=True,
                help_text="Detailed learning objectives for the course",
                verbose_name="Learning Objectives",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=models.TextField(
                blank=True,
                help_text="Required knowledge or courses before taking this course",
                verbose_name="Prerequisites",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("ARCHIVED", "Archived"),
                    ("DEPRECATED", "Deprecated"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Course Status",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Current version number of the course",
                verbose_name="Current Version",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="version_notes",
            field=models.TextField(blank=True, verbose_name="Version Notes"),
        ),
        migrations.AddField(
            model_name="course",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PRIVATE", "Private"),
                    ("INTERNAL", "Internal"),
                    ("PUBLIC", "Public"),
                ],
                default="PRIVATE",
                max_length=20,
                verbose_name="Course Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Course Title",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("title", "version")},
        ),
        migrations.CreateModel(
            name="StatusTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        max_length=20,
                        verbose_name="From Status",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        max_length=20,
                        verbose_name="To Status",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Changed At"),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Transition Reason"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed By",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_transitions",
                        to="learning.course",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Status Transitions",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="InstructorRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        choices=[
                            ("LEAD", "Lead Instructor"),
                            ("ASSISTANT", "Assistant Instructor"),
                            ("GUEST", "Guest Instructor"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Role Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Role Description"),
                ),
                (
                    "can_edit_course",
                    models.BooleanField(default=False, verbose_name="Can Edit Course"),
                ),
                (
                    "can_manage_tasks",
                    models.BooleanField(default=False, verbose_name="Can Manage Tasks"),
                ),
                (
                    "can_grade_submissions",
                    models.BooleanField(
                        default=False, verbose_name="Can Grade Submissions"
                    ),
                ),
            ],
            options={
                "unique_together": {("role_name",)},
            },
        ),
        migrations.CreateModel(
            name="CourseInstructorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_assignments",
                        to="learning.course",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_instructor_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_assignments",
                        to="learning.instructorrole",
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "instructor")},
            },
        ),
        migrations.RemoveField(
            model_name="course",
            name="instructor",
        ),
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses_taught",
                through="learning.CourseInstructorAssignment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CourseVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="Sequential version number for this course",
                        verbose_name="Version Number",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about changes in this version",
                        verbose_name="Version Notes",
                    ),
                ),
                (
                    "content_snapshot",
                    models.JSONField(
                        help_text="Snapshot of course content at this version",
                        verbose_name="Content Snapshot",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="learning.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_versions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "get_latest_by": "version_number",
                "unique_together": {("course", "version_number")},
            },
        ),
    ]
