# Generated by Django 4.2.9 on 2025-03-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_quizattempt_taskprogress_quizresponse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskprogress",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
