# Generated by Django 4.2.9 on 2025-03-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_taskprogress_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="courseenrollment",
            options={"ordering": ["-enrollment_date"]},
        ),
    ]
