# Generated by Django 4.2.9 on 2025-03-28 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_course_options_alter_courseenrollment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
