# Generated by Django 4.2.9 on 2025-03-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_course_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningtask",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_tasks",
                to="core.course",
            ),
        ),
    ]
