name: Backend Tests

on:
  push:
    branches:
      - main

jobs:
  safety:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: | 
          pip install safety

      - name: Run safety scan
        run: safety check --json > safety_results.json

      - name: Upload safety results
        uses: actions/upload-artifact@v2
        with:
          name: safety-results
          path: safety_results.json