# E2E Tests - TEMPORARILY DISABLED
#
# These tests have been temporarily disabled due to infrastructure complexity.
# They will be reconfigured to run against preprod environment.
# See: memory_bank/current/backlog/active/TASK-E2E-PREPROD-INTEGRATION.md

name: E2E Tests

on:
  workflow_call:
jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: E2E Tests Disabled
        run: echo "E2E tests are temporarily disabled - will be reconfigured for preprod environment"